from pathlib import Path
import json

import numpy as np
import pandas as pd
from scipy.sparse import load_npz


class RecommendationModelLoader:
    """
    Loads the ML artifacts generated by Phase 8.

    Artifacts:
    - weighted_matrix.npz
    - phase2_movies.csv
    - cf_user_ids.npy
    - cf_movie_ids.npy
    - cf_user_factors.npy
    - cf_movie_factors.npy
    - model_config.json
    - model_metadata.json
    """

    def __init__(self):
        self.project_root = Path(__file__).resolve().parents[3]

        self.model_dir = (
            self.project_root
            / "ml"
            / "model_artifacts"
        )

        self._load()

    def _load(self):
        if not self.model_dir.exists():
            raise FileNotFoundError(
                f"ML model directory not found: {self.model_dir}"
            )

        print("=" * 60)
        print("Loading ML recommendation artifacts")
        print("=" * 60)

        # Content-based model
        self.weighted_matrix = load_npz(
            self.model_dir / "weighted_matrix.npz"
        )

        self.movies = pd.read_csv(
            self.model_dir / "phase2_movies.csv"
        )

        # Collaborative filtering model
        self.user_ids = np.load(
            self.model_dir / "cf_user_ids.npy"
        )

        self.movie_ids = np.load(
            self.model_dir / "cf_movie_ids.npy"
        )

        self.user_factors = np.load(
            self.model_dir / "cf_user_factors.npy"
        )

        self.movie_factors = np.load(
            self.model_dir / "cf_movie_factors.npy"
        )

        # Configuration
        self.config = self._load_json(
            "model_config.json"
        )

        self.metadata = self._load_json(
            "model_metadata.json"
        )

        # Runtime mappings
        self.user_to_index = {
            int(user_id): index
            for index, user_id in enumerate(self.user_ids)
        }

        self.movie_to_index = {
            int(movie_id): index
            for index, movie_id in enumerate(
                self.movies["movieId"]
            )
        }

        self.cf_movie_to_index = {
            int(movie_id): index
            for index, movie_id in enumerate(
                self.movie_ids
            )
        }

        self._validate()

        print("ML artifacts loaded successfully")
        print(f"Movies: {len(self.movies)}")
        print(
            f"Content matrix: "
            f"{self.weighted_matrix.shape}"
        )
        print(
            f"CF users: "
            f"{self.user_factors.shape}"
        )
        print(
            f"CF movies: "
            f"{self.movie_factors.shape}"
        )
        print(
            f"Model version: "
            f"{self.config.get('model_version')}"
        )
        print("=" * 60)

    def _load_json(self, filename: str):
        file_path = self.model_dir / filename

        with open(
            file_path,
            "r",
            encoding="utf-8"
        ) as file:
            return json.load(file)

    def _validate(self):
        if (
            self.weighted_matrix.shape[0]
            != len(self.movies)
        ):
            raise ValueError(
                "Weighted matrix rows do not match movie count"
            )

        if (
            self.user_factors.shape[0]
            != len(self.user_ids)
        ):
            raise ValueError(
                "User factors do not match user IDs"
            )

        if (
            self.movie_factors.shape[0]
            != len(self.movie_ids)
        ):
            raise ValueError(
                "Movie factors do not match movie IDs"
            )

        content_weight = self.config.get(
            "content_weight"
        )

        collaborative_weight = self.config.get(
            "collaborative_weight"
        )

        if (
            content_weight is None
            or collaborative_weight is None
        ):
            raise ValueError(
                "Recommendation weights are missing "
                "from model_config.json"
            )

        if abs(
            content_weight
            + collaborative_weight
            - 1.0
        ) > 1e-6:
            raise ValueError(
                "Content and collaborative weights "
                "must sum to 1.0"
            )